#!/usr/bin/env bash
set -euo pipefail
here="$(cd "$(dirname "${BASH_SOURCE[0]}")"&&pwd)";root="${PUSCH_MIMO_CLEAN_KERNEL_ROOT:-/home/refresh/AI-RAN-NPU-clean/kernels}";ascend_home="${ASCEND_HOME_PATH:-/usr/local/Ascend/ascend-toolkit/latest}";work="${here}/work/tx_prefix_rank1";logs="${here}/logs/demod_rank1";mkdir -p "$logs"
source "${here}/build_variant.sh";load_mimo_build_variant 1
set +e;set +u;if [[ -f "${ascend_home}/bin/setenv.bash" ]];then source "${ascend_home}/bin/setenv.bash";else source "${ascend_home}/set_env.sh";fi;set -u;set -e
build(){ local tag="$1" rel="$2";cmake -S "${root}/${rel}" -B "${here}/build/${tag}" -DRUN_MODE=npu -DSOC_VERSION=Ascend310P1 -DASCEND_CANN_PACKAGE_PATH="${ascend_home}" -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX="${here}/out/${tag}" >"${logs}/build_${tag}.log" 2>&1;cmake --build "${here}/build/${tag}" -j "$(nproc)" >>"${logs}/build_${tag}.log" 2>&1;cmake --install "${here}/build/${tag}" >>"${logs}/build_${tag}.log" 2>&1;}
build qam_demod_256_mimo_batch mapping/qam_demod_256_mimo_batch;build layer_demap_mimo mapping/layer_demap_mimo
g++ -O2 -std=c++17 -D_GLIBCXX_USE_CXX11_ABI=0 -Wall -Wextra -Werror -I"${root}/mapping/qam_demod_256_mimo_batch" -I"${root}/common" -I"${here}/out/qam_demod_256_mimo_batch/include/ascendc_kernels_npu" -I"${ascend_home}/include" "${here}/qam_demod_stage.cpp" "${root}/common/pusch_mimo_runtime_config.cpp" "${root}/mapping/qam_demod_256_mimo_batch/qam256_demod_batch.cpp" "${root}/mapping/qam_demod_256_mimo_batch/qam256_demod_batch_contract.cpp" -L"${here}/out/qam_demod_256_mimo_batch/lib" -lascendc_kernels_npu -L"${ascend_home}/lib64" -lascendcl -lplatform -lregister -ltiling_api -lascendalog -ldl -o "${here}/out/qam_demod_256_mimo_batch/bin/pusch_mimo_qam_demod_stage" >>"${logs}/build_qam_demod_256_mimo_batch.log" 2>&1
g++ -O2 -std=c++17 -D_GLIBCXX_USE_CXX11_ABI=0 -Wall -Wextra -Werror -I"${root}/mapping/layer_demap_mimo" -I"${root}/common" -I"${here}/out/layer_demap_mimo/include/ascendc_kernels_npu" -I"${ascend_home}/include" "${here}/layer_demap_stage.cpp" "${root}/common/pusch_mimo_runtime_config.cpp" "${root}/mapping/layer_demap_mimo/layer_demap.cpp" -L"${here}/out/layer_demap_mimo/lib" -lascendc_kernels_npu -L"${ascend_home}/lib64" -lascendcl -lplatform -lregister -ltiling_api -lascendalog -ldl -o "${here}/out/layer_demap_mimo/bin/pusch_mimo_layer_demap_stage" >>"${logs}/build_layer_demap_mimo.log" 2>&1
det="${work}/detect/data/ascend_output/case_0_m${mimo_detector_rx_capacity}_k${mimo_detector_layer_capacity}_sc1664_r1";mkdir -p "${work}/artifacts/demod"
LD_LIBRARY_PATH="${here}/out/qam_demod_256_mimo_batch/lib:${ascend_home}/lib64:${LD_LIBRARY_PATH:-}" "${here}/out/qam_demod_256_mimo_batch/bin/pusch_mimo_qam_demod_stage" "$det" "${work}/artifacts/demod/slot00_layer_llr.bin" 1 | tee "${logs}/qam_slot00.log"
LD_LIBRARY_PATH="${here}/out/layer_demap_mimo/lib:${ascend_home}/lib64:${LD_LIBRARY_PATH:-}" "${here}/out/layer_demap_mimo/bin/pusch_mimo_layer_demap_stage" "${work}/artifacts/demod/slot00_layer_llr.bin" "${work}/artifacts/demod/slot00_cw_llr.bin" 1 | tee "${logs}/layer_slot00.log"
