#include <acl/acl.h>
#include "scramble_mimo.h"
#include <algorithm>
#include <cstdint>
#include <cstdio>
#include <fstream>
#include <string>
#include <vector>
namespace op=airan::scramble_mimo;
#define OK(x) do{aclError e=(x);if(e!=ACL_ERROR_NONE){std::fprintf(stderr,"[HARD_FAIL] %s=%d\n",#x,e);return 1;}}while(0)
airan::PuschMimoConfig Cfg(unsigned l){airan::PuschMimoConfig c{};c.abi_version=1;c.struct_size=sizeof(c);c.num_layers=l;c.num_tx_ports=l==1?1:(l==2?2:4);c.num_rx_antennas=64;c.qm=8;c.num_symbols=14;c.fft_size=2048;c.num_rb=133;c.num_allocated_symbols=14;c.used_subcarriers=1596;c.padded_subcarriers=1664;c.dmrs_symbol_mask=(1u<<2)|(1u<<11);c.data_scrambling_id=321;c.rnti=12345;c.dmrs_type=1;c.dmrs_length=1;c.num_cdm_groups_without_data=2;return c;}
int main(int ac,char**av){if(ac!=4)return 2;unsigned l=std::stoul(av[3]);if(l<1||l>4)return 2;size_t n=op::BufferElems(23,l);std::ifstream f(av[1],std::ios::binary|std::ios::ate);if(!f||size_t(f.tellg())!=n*2)return 1;std::vector<int16_t> in(n),sign(n),ref(n),out(n);f.seekg(0);f.read((char*)in.data(),n*2);auto c=Cfg(l);airan::PuschMimoLayout lay{};op::KernelMetadata meta{};if(op::BuildCurrentProfile(c,23,&lay,&meta)!=op::OK||op::BuildGoldBits(c,lay,23,sign.data(),n)!=op::OK||op::ReferenceScramble(in.data(),sign.data(),c,lay,23,ref.data())!=op::OK)return 1;OK(aclInit(nullptr));OK(aclrtSetDevice(0));aclrtStream s;OK(aclrtCreateStream(&s));void *di,*dg,*doo,*dw,*dt;OK(aclrtMalloc(&di,n*2,ACL_MEM_MALLOC_HUGE_FIRST));OK(aclrtMalloc(&dg,n*2,ACL_MEM_MALLOC_HUGE_FIRST));OK(aclrtMalloc(&doo,n*2,ACL_MEM_MALLOC_HUGE_FIRST));OK(aclrtMalloc(&dw,op::WORKSPACE_BYTES,ACL_MEM_MALLOC_HUGE_FIRST));OK(aclrtMalloc(&dt,op::TILING_BYTES,ACL_MEM_MALLOC_HUGE_FIRST));OK(aclrtMemcpy(di,n*2,in.data(),n*2,ACL_MEMCPY_HOST_TO_DEVICE));OK(aclrtMemcpy(dg,n*2,sign.data(),n*2,ACL_MEMCPY_HOST_TO_DEVICE));OK(aclrtMemcpy(dt,sizeof(meta),&meta,sizeof(meta),ACL_MEMCPY_HOST_TO_DEVICE));op::ScrambleMimoOpArgsV1 a{};a.abi_version=1;a.struct_size=sizeof(a);a.bits_nr=di;a.bits_qam=doo;a.config=&c;a.layout=&lay;a.num_slots=23;a.stream=s;if(op::Enqueue(a,dg,n*2,dw,op::WORKSPACE_BYTES,dt,op::TILING_BYTES)!=op::OK)return 1;OK(aclrtSynchronizeStream(s));OK(aclrtMemcpy(out.data(),n*2,doo,n*2,ACL_MEMCPY_DEVICE_TO_HOST));if(out!=ref)return 1;std::ofstream o(av[2],std::ios::binary|std::ios::trunc);o.write((char*)out.data(),n*2);if(!o)return 1;for(void*p:{dt,dw,doo,dg,di}){aclrtFree(p);}OK(aclrtDestroyStream(s));OK(aclrtResetDevice(0));OK(aclFinalize());std::printf("[PASS] scramble_mimo Rank%u slots=23 bit-exact\n",l);return 0;}
